#!/usr/bin/env bash

set -euo pipefail

( sed facts/recipes -E -e 's/^.+<- //'
  sed facts/begets -E -e 's/ -> .+$//'
  sed mixologic.dl -En -e 's/^Begets\("([^"]+).+\.$/\1/; T; p'
) \
| grep -vFf <(cat facts/auto-unbuyable facts/unbuyable) \
| sort -u
